# Test your FastAPI endpoints

GET http://127.0.0.1:8000/health
Accept: application/json

###

POST http://127.0.0.1:8000/train
Content-Type: application/json

###

POST http://127.0.0.1:8000/predict-daily
Content-Type: application/json

###
