// <auto-generated />
using System;
using Inferra.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inferra.Infrastructure.Migrations
{
    [DbContext(typeof(InferraDbContext))]
    [Migration("20260607215252_AddedIsNewsEnabled")]
    partial class AddedIsNewsEnabled
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inferra.Domain.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CirculatingSupply")
                        .HasPrecision(38, 8)
                        .HasColumnType("decimal(38,8)");

                    b.Property<string>("CoinGeckoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsMlEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNewsEnabled")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxSupply")
                        .HasPrecision(38, 8)
                        .HasColumnType("decimal(38,8)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PairSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("TotalSupply")
                        .HasPrecision(38, 8)
                        .HasColumnType("decimal(38,8)");

                    b.HasKey("Id");

                    b.HasIndex("PairSymbol")
                        .IsUnique();

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.DailyCandle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Date")
                        .IsUnique();

                    b.ToTable("DailyCandles");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.ForecastPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<int>("DayOffset")
                        .HasColumnType("int");

                    b.Property<int>("ForecastRunId")
                        .HasColumnType("int");

                    b.Property<decimal?>("LowerBound")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("PredictedPrice")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateOnly>("TargetDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("UpperBound")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.HasKey("Id");

                    b.HasIndex("ForecastRunId", "DayOffset")
                        .IsUnique();

                    b.HasIndex("ForecastRunId", "TargetDate")
                        .IsUnique();

                    b.ToTable("ForecastPoints");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.ForecastRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ForecastEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ForecastStartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorizonDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsLatest")
                        .HasColumnType("bit");

                    b.Property<int>("ModelType")
                        .HasColumnType("int");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "ModelType", "GeneratedAt");

                    b.HasIndex("AssetId", "ModelType", "IsLatest");

                    b.ToTable("ForecastRuns");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.MarketSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FullyDilutedValuation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceChange24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PriceChangePercentage24h")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Volume24h")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("MarketSnapshots");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.SentimentSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<int>("Bearish")
                        .HasColumnType("int");

                    b.Property<int>("Bullish")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Neutral")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .IsUnique();

                    b.ToTable("SentimentSnapshots");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.DailyCandle", b =>
                {
                    b.HasOne("Inferra.Domain.Entities.Asset", "Asset")
                        .WithMany("DailyCandles")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.ForecastPoint", b =>
                {
                    b.HasOne("Inferra.Domain.Entities.ForecastRun", "ForecastRun")
                        .WithMany("Points")
                        .HasForeignKey("ForecastRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForecastRun");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.ForecastRun", b =>
                {
                    b.HasOne("Inferra.Domain.Entities.Asset", "Asset")
                        .WithMany("ForecastRuns")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.MarketSnapshot", b =>
                {
                    b.HasOne("Inferra.Domain.Entities.Asset", "Asset")
                        .WithOne("MarketSnapshot")
                        .HasForeignKey("Inferra.Domain.Entities.MarketSnapshot", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.SentimentSnapshot", b =>
                {
                    b.HasOne("Inferra.Domain.Entities.Asset", "Asset")
                        .WithOne("SentimentSnapshot")
                        .HasForeignKey("Inferra.Domain.Entities.SentimentSnapshot", "AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.Asset", b =>
                {
                    b.Navigation("DailyCandles");

                    b.Navigation("ForecastRuns");

                    b.Navigation("MarketSnapshot");

                    b.Navigation("SentimentSnapshot");
                });

            modelBuilder.Entity("Inferra.Domain.Entities.ForecastRun", b =>
                {
                    b.Navigation("Points");
                });
#pragma warning restore 612, 618
        }
    }
}
